spring.application.name=prodigo-erp

# jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:jobportal}
spring.datasource.url=jdbc:postgresql://localhost:5432/prodigodb
spring.datasource.username=postgres
spring.datasource.password=@azerty237
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.default_schema=
#spring.jpa.properties.hibernate.dialect=
spring.jpa.show-sql=true

# JWT

security.jwt.secret=2XZCFnmx0gac6Obn7LVsXtxpT36eCKJBGEbXg3luFuN2
# 15 min
security.jwt.expiration=900000
# 7 days
security.jwt.refresh-expiration=604800000


#
logging.level.org.springframework.security=DEBUG